apiVersion: v1
kind: Service
metadata:
  name: s3-chart-museum
  namespace: autoci
  labels:
    app: s3-chart-museum
spec:
    type: LoadBalancer
    selector:
        app: s3-chart-museum
    ports:
    - name: repository
      targetPort: 8080
      protocol: TCP
      port: 80