apiVersion: v1
kind: Service
metadata:
  name: autoci-azure-svc
  namespace: autoci
spec:
  type: NodePort
  selector:
    app: autoci-azure
  ports:
  - name: web-interface
    protocol: TCP
    nodePort: 30120
    port: 8080
    targetPort: 8080