apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: project3 #(TBD)
  name: nginx-deployment # TBD, testing using nginx
  #More TBD
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx # TBD, testing using nginx
        image: nginx:1.14.2 # TBD, testing using nginx
        imagePullPolicy: Always
        #volumeMounts:
        #- name:
        #- mountPath:
      
# use service to set other info...
