apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Service
metadata:
  namespace: project3
  name: testserver-service
spec:
  type: NodePort
  selector:
    app: testserver
  ports:
    - name: sample
      port: 8080
      targetPort: 8080
      nodePort: 30001

  