apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: project3 #(TBD)
  name: testserver-deployment # TBD, testing using nginx
  #More TBD
spec:
  selector:
    matchLabels:
      app: testserver
  replicas: 1 
  template:
    metadata:
      labels:
        app: testserver
    spec:
      containers:
      - name: testserver # TBD, testing using nginx
        image: reblank/autoci-init # TBD, testing using nginx
        imagePullPolicy: Always
        #volumeMounts:
        #- name:
        #- mountPath:
      
# use service to set other info...
