apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: autoci
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - name: web-interface
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: remote-java-api
    protocol: TCP
    port: 50000
    targetPort: 50000