package com.revature.autoci.init.generators;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import com.revature.autoci.init.generators.utils.Templater;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class provides static methods for generating the Spinnaker pipeline file.
 * In general, the Spinnaker pipeline is not intended to change after initial generation,
 * however it is possible to modify the pipeline file and trigger the pipeline to 
 * be regenerated by making the correct call to the Spinnaker REST endpoint.
 */
public class GenerateSpinnaker {
    private static final Logger log = LoggerFactory.getLogger(GenerateSpinnaker.class);
    /**
     * Generates a Jenkinsfile from a template. The template used depends on whether it is a Maven or NPM project.
     * 
     * @param projectName The name of this project
     * @param pathToProject The path to the directory where the pipeline file will be placed
     * @param imageName The name of the Docker image for this project
     * */ 
    public static void generateSpinnaker(String projectName, String pathToProject, String imageName) throws IOException
    {
        // Compile regex to replace variables with arguments
        Map<String, String> pairs = new HashMap<>();
        pairs.put("projectName", projectName);
        pairs.put("jenkinsName", projectName.toLowerCase());
        pairs.put("pipelineId", projectName + UUID.randomUUID().toString());
        pairs.put("imageName", imageName);
        Templater templater = new Templater(pairs);

        // Determine the template to use
        String template = "spinnaker.json";

        // Fill in the template and create new Spinnaker Pipeline
        InputStream templateStream = GenerateSpinnaker.class.getClassLoader().getResourceAsStream(template);
        try(BufferedReader buf = new BufferedReader(new InputStreamReader(templateStream)))       
        {
            File spinnaker = Paths.get(pathToProject,"Spinnaker.json").toFile();
            spinnaker.createNewFile();
            try(FileWriter writer = new FileWriter(spinnaker))
            {
                templater.fillTemplate(buf, writer, "");
                log.info("Spinnaker Pipeline Template successfully updated");
            }
        }
    }
}
