apiVersion: v1
kind: Service
metadata:
  name: autoci-config-svc
spec:
  type: NodePort
  selector:
    app: autoci-config
  ports:
  - name: web-interface
    protocol: TCP
    nodePort: 30100
    port: 8080
    targetPort: 8080