apiVersion: v1
kind: Service
metadata:
  name: spinnaker-service
  namespace: spinnaker-service
  labels:
    app: spinnaker-service
spec:
    type: LoadBalancer
    selector:
        app: spinnaker-receiver
    ports:
    - name: tomcat
      port: 8080
      protocol: TCP