apiVersion: v1
kind: Service
metadata:
  name: autoci-jenkins-svlt-svc
  namespace: autoci
spec:
  type: NodePort
  selector:
    app: autoci-jenkins-svlt
  ports:
  - name: web-interface
    protocol: TCP
    nodePort: 30110
    port: 8080
    targetPort: 8080