apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoci-jenkins-svlt
  namespace: autoci
  labels:
    app: autoci-jenkins-svlt
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: autoci-jenkins-svlt
  template:
    metadata:
      labels:
        app: autoci-jenkins-svlt
    spec:
      containers:
        - name: autoci-jenkins-svlt
          image: alxl/autoci-jenkins-svlt:latest
          ports:
          - containerPort: 8080
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: terraform-aws
                key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: terraform-aws
                key: secret_access_key
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: terraform-aws
                key: default_region